### ISSUE TITLE
Add support for Factions 2.7.0+

### ISSUE THREAD

**Issue by AmalMohan** [MarkehMe/FactionsPlus#172]
Just updated to factions 2.7.0 and looks like the plugin not loading at all.

**Comment by franga2000** [comment]
Any progress on the update? `2.7.4` still gives me a bunch of `NoClassDefFound` errors.

**Comment by MarkehMe** [comment]
Downgrade and wait for now. The entire plugin is being recoded to support all versions of Factions.

**Comment by Aedenia** [comment]
hi :)  news  ? for the update 2.7 ?  thanks.

**Comment by MarkehMe** [comment]
It's quite a lot of work to remove the universe system, so I've been pushing major features into the main plugin if Factions until I have time to rebuild the entire plugin

**Comment by MarkehMe** [comment]
Fixed in FactionsPlus 2.0
