### ISSUE TITLE
FactionsPlus have a problem with MassiveCore

### ISSUE THREAD

**Issue by AnonymousMW3** [MarkehMe/FactionsPlus#175]
Version of FactionsPlus: 0.7.1(the last build)
Version of Factions: 2.7.4(the last build)
Version of MassiveCore: 2.7.4(the last build)
Version of Spigot: 1.8(the last build)
Pastebin of the error: http://pastebin.com/9y8RX7hn
Please read, i think if it's important!

**Comment by coolemiel** [comment]
Same problem here! Really annoying...

**Comment by AnonymousMW3** [comment]
I hope that there will soon be an update!

**Comment by MarkehMe** [comment]
Duplicate of #172
