### ISSUE TITLE
FactionsUUID Compatibility

### ISSUE THREAD

**Issue by drtshock** [MarkehMe/FactionsPlus#178]
As I saw in the comments on your page and mine now, you are looking to add compatibility <3 Now, my project is open source so you're free to clone and just mvn clean install it so it's in your local .m2, no need to purchase.

I'm here offering assistance to make sure everything is compatible. I know that my project has a few of the features included in your project so it's best to be sure that if that's the case, they play nicely. You can find my project here https://github.com/drtshock/Factions. If you need any help, feel free to add me on skype (drtshock13) or join #drtshock on espernet.

Since you'll be building against multiple versions of a plugin, that can get quite tricky. An example of how to do that with Factions can be found here https://github.com/drtshock/ObsidianDestroyer. I'd prefer you don't keep a binary of my project in your repo as it's not necessary :)

**Comment by MarkehMe** [comment]
Thanks for the hints! I'm thinking of using reflection but read online that it can be rather slow. 

Will take a look at your project over the weekend, thanks!

**Comment by MarkehMe** [comment]
Will be in FactionsPlus 2.0
