### ISSUE TITLE
lang FR

### ISSUE THREAD

**Issue by Aedenia** [MarkehMe/FactionsPlus#180]
Hi,

I want create traduction FR , how i can ?

**Comment by MarkehMe** [comment]
Inside mstore look for the LConf file! :)

**Comment by Aedenia** [comment]
ohhh great !  thanks.   And  we can change factions ? or we need change plugins.

**Comment by MarkehMe** [comment]
I don't 100% understand what you mean buy you require Factions 2.5.0 and the Massive Core to go along with it.
