### ISSUE TITLE
Sorry, your ranking is not high enough to create warps!

### ISSUE THREAD

**Issue by Delliurm** [MarkehMe/FactionsPlus#182]
I am running Factions V1.8.2-U0.7. I am using factions plus version 0.5.2. In order to get this factions to work on spigot I had to have the plugin re-worked so that it would use the mcore database instead of gson library, since paperspigot has none. Regardless this fixed it and every aspect of the factions plugin works fine. I recently installed the factionsplus and it loads perfect, no errors. I can see all the added commands in the /f help list. The only problem is this. Every time I try to create a warp it says 'Sorry, your ranking is not high enough to create warps!' It does not matter if I am leader, officer, or even member. When I try to create a f announce I get this message. 'Sorry, your ranking is not high enough to do that!'

Here is my factionsplus config, short version ;)
### 
### default value: true
enabled: true
### 
### default value: true
leadersCanSetWarps: true
### 
### default value: true
officersCanSetWarps: true
### 
### default value: false
membersCanSetWarps: false
### 
### when false, allows you to create and teleport to warps in any places even if they are in enemy land
mustBeInOwnTerritoryToCreate: true
### 
### if true, you cannot teleport to a warp residing inside enemy land
denyWarpToEnemyLand: true

Any suggestions?

**Comment by MarkehMe** [comment]
Yikes, quite an old version of FactionsPlus. 0.7.1 is the most stable version out. 0.5.2 is not very stable, maybe even try 0.5.3 (http://dev.bukkit.org/bukkit-plugins/factionsplus/files/30-factions-plus-0-5-3/) 

Factions Plus 0.7.1: http://dev.bukkit.org/bukkit-plugins/factionsplus/files/50-factions-plus-v0-7-1/

I suggest upgrading to the plugins listed as the tested versions (newer versions of Vault may work, but it's quite untested):
```
Tested with Factions 2.5.0
Tested with Vault 1.4.1-b436
```

Factions 2.5.0: http://dev.bukkit.org/bukkit-plugins/factions/files/67-factions-2-5-0-massive-core-7-3-0-for-cb-1-7-10/
MassiveCore 7.3.0: http://dev.bukkit.org/bukkit-plugins/mcore/files/35-old-massive-core-7-3-0-for-cb-1-7-10/

I remember fixing this issue a long time ago, so it's best to upgrade :)

**Comment by Delliurm** [comment]
Thing is, im creating a factions server, and seems that the most dedicated faction players, and servers, like gontroller, use the factions version I am using. It is what everyone is use to and like the most. I have tried a few other faction plus versions with Factions V1.8.2-U0.7. Yet this is the only version I can get to load, all the others have errors. Do you know of one that would work with this? Most are paperspigot errors, and yes I have to use paperspigot too. I just didnt know if this was a simple fix or not.

**Comment by MarkehMe** [comment]
Unfortunately a lot of work is required on the older versions of FactionsPlus. I am how've helping upstream with Factions now. 

So, if you let me know what features are missing I can implement them into Factions!

**Comment by Delliurm** [comment]
My questions is this, I can pay you to fix this for me. Since you are the creator of the f plus plugin I figured it would be easiest for you. Ive had a few devs look into it and they are having issues. If I give you my paperspigot, my mcore, my factions and the fplus i use. Can you fix it for me? Again I will pay you whatever you ask. Seems the problem is the fplus dosent use uuid, and my factions does. Every time I create a faction I get an error from f plus. The factions plugin i have is modified to use mcore.

**Comment by MarkehMe** [comment]
@Delliurm I can take a look into this. Can you add me on Skype - markehme
