### ISSUE TITLE
No Mstore config

### ISSUE THREAD

**Issue by EliasXOF** [MarkehMe/FactionsPlus#185]
Recently I found that by accident when I deleted my mstore config for maintenance there was no longer a FactionsPlus config for mstore and now I am kinda...wondering how I'm gonna work that out without having to take the whole server apart.

Is there a way or a place I can find the mstore folders for FactionsPlus?
23.12 03:41:40 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
23.12 03:41:40 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:536) [craftbukkit-1.8.8.jar:git-Bukkit-de5c261]
23.12 03:41:40 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:628) [craftbukkit-1.8.8.jar:git-Bukkit-de5c261]
23.12 03:41:40 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [craftbukkit-1.8.8.jar:git-Bukkit-de5c261]
23.12 03:41:40 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:679) [craftbukkit-1.8.8.jar:git-Bukkit-de5c261]
23.12 03:41:40 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [craftbukkit-1.8.8.jar:git-Bukkit-de5c261]
23.12 03:41:40 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit-1.8.8.jar:git-Bukkit-de5c261]
23.12 03:41:40 [Server] INFO at nl.maloengaming.SimpleBroadcaster.Main$1.run(Main.java:52) ~[?:?]
23.12 03:41:40 [Server] INFO at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_45]
23.12 03:41:40 [Server] INFO at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_45]
23.12 03:41:40 [Server] INFO java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
23.12 03:41:40 [Server] WARN Task #38 for SimpleBroadcaster v1.1.1 generated an exception
23.12 03:41:34 [Server] INFO [Error] Please upload to pastebin.com and include in any error reports.
23.12 03:41:34 [Server] INFO [Error] It has been saved to plugins/FactionsPlus/logs/1450838494116.errorlog
23.12 03:41:34 [Server] WARN ... 22 more
23.12 03:41:34 [Server] WARN at java.lang.ClassLoader.loadClass(Unknown Source)
23.12 03:41:34 [Server] WARN at java.lang.ClassLoader.loadClass(Unknown Source)
23.12 03:41:34 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62)
23.12 03:41:34 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77)
23.12 03:41:34 [Server] WARN at java.net.URLClassLoader.findClass(Unknown Source)
23.12 03:41:34 [Server] WARN Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.ChatColor
23.12 03:41:34 [Server] WARN at java.lang.Thread.run(Unknown Source)
23.12 03:41:34 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:536)
23.12 03:41:34 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:628)
23.12 03:41:34 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335)
23.12 03:41:34 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:672)
23.12 03:41:34 [Server] WARN at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
23.12 03:41:34 [Server] WARN at java.util.concurrent.FutureTask.run(Unknown Source)
23.12 03:41:34 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
23.12 03:41:34 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
23.12 03:41:34 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:9)
23.12 03:41:34 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:37)
23.12 03:41:34 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:966)
23.12 03:41:34 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1106)
23.12 03:41:34 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:619)
23.12 03:41:34 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
23.12 03:41:34 [Server] WARN at com.massivecraft.massivecore.cmd.MassiveCoreBukkitCommand.execute(MassiveCoreBukkitCommand.java:61)
23.12 03:41:34 [Server] WARN at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:649)
23.12 03:41:34 [Server] WARN at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:596)
23.12 03:41:34 [Server] WARN at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:617)
23.12 03:41:34 [Server] WARN at me.markeh.factionsframework.command.versions.FactionsCommand2XWrapper.perform(FactionsCommand2XWrapper.java:97)
23.12 03:41:34 [Server] WARN at me.markeh.factionsframework.command.FactionsCommand.preRun(FactionsCommand.java:89)
23.12 03:41:34 [Server] WARN at me.markeh.factionsframework.objs.Perm.has(Perm.java:32)
23.12 03:41:34 [Server] WARN java.lang.NoClassDefFoundError: net/md_5/bungee/api/ChatColor
23.12 03:41:34 [Server] INFO [Error] Oh no, an internal error has occurred! :-(

Also this happened...

Server is 1.8.8 CraftBukkit

**Comment by MarkehMe** [comment]
Doesn't use mstore anymore, uses it's own configuration.

Please use Spigot! :smile: ```java.lang.NoClassDefFoundError: net/md_5/bungee/api/ChatColor``` it's looking for a spigot class

**Comment by ChrisLane** [comment]
@MarkehMe Why not just use the `org.bukkit.ChatColor` import instead?

**Comment by MarkehMe** [comment]
I probably witched it back by now, it was Eclipse doing its own thing :grin:

**Comment by ChrisLane** [comment]
Nope :smile: https://github.com/MarkehMe/FactionsPlus/blob/c730cb4cde5e31991ef27f675938b79626b7a1fe/src/me/markeh/factionsframework/objs/Perm.java#L5
