### ISSUE TITLE
Instances

### ISSUE THREAD

**Issue by EliasXOF** [MarkehMe/FactionsPlus#186]
So after using Spigot 1.8.8 and abandoning mstore. There seems to be no way to edit the instances and or the errors of the Instances
When I type /f addrule it will say <red>you don't have permission to view the rules
also I can enable them only to get an error in the console which apparently is asking for Spigot even though I'm using Spigot already.

**Comment by MarkehMe** [comment]
Have you given the permission to add rules? 

https://github.com/MarkehMe/FactionsPlus/wiki/Permissions
