### ISSUE TITLE
More splendid errors

### ISSUE THREAD

**Issue by EliasXOF** [MarkehMe/FactionsPlus#188]
26.12 06:39:36 [Server] INFO [Error] It has been saved to plugins/FactionsPlus/logs/1451108376702.errorlog
26.12 06:39:36 [Server] WARN at java.lang.Thread.run(Unknown Source)
26.12 06:39:36 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
26.12 06:39:36 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
26.12 06:39:36 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
26.12 06:39:36 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714)
26.12 06:39:36 [Server] WARN at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
26.12 06:39:36 [Server] WARN at java.util.concurrent.FutureTask.run(Unknown Source)
26.12 06:39:36 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
26.12 06:39:36 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
26.12 06:39:36 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
26.12 06:39:36 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
26.12 06:39:36 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
26.12 06:39:36 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
26.12 06:39:36 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:640)
26.12 06:39:36 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
26.12 06:39:36 [Server] WARN at com.massivecraft.massivecore.cmd.MassiveCoreBukkitCommand.execute(MassiveCoreBukkitCommand.java:61)
26.12 06:39:36 [Server] WARN at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:649)
26.12 06:39:36 [Server] WARN at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:596)
26.12 06:39:36 [Server] WARN at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:617)
26.12 06:39:36 [Server] WARN at me.markeh.factionsframework.command.versions.FactionsCommand2XWrapper.perform(FactionsCommand2XWrapper.java:100)
26.12 06:39:36 [Server] WARN at me.markeh.factionsplus.commands.CmdWarp.run(CmdWarp.java:84)
26.12 06:39:36 [Server] WARN at org.bukkit.Location.distanceSquared(Location.java:456)
26.12 06:39:36 [Server] WARN java.lang.IllegalArgumentException: Cannot measure distance between flatworld and world

Every fix I've found for this doesn't make a lick of sense since I don't know anything about code.

**Comment by MarkehMe** [comment]
I've made a fix for this issue and it's being uploaded soon.

**Comment by MarkehMe** [comment]
Also, please upload the file plugins/FactionsPlus/logs/1451108376702.errorlog to pastebin
