### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by bencerda1** [MarkehMe/FactionsPlus#190]
Whenever I try to use /f setwwarp or /f setjail (maybe others, haven't tried) I get these errors:
Setwarp: http://pastebin.com/eRb6envu
Setjail: http://pastebin.com/4p5Wg61w

**Comment by MarkehMe** [comment]
Apologies for the delay, I've been busy of the christmas and new year break! 

I will look into this for you. Oddly, no one else has reported this issue.

**Comment by MarkehMe** [comment]
Should not be an issue anymore, if it is please open a new ticket
