### ISSUE TITLE
Errors still happening

### ISSUE THREAD

**Issue by bencerda1** [MarkehMe/FactionsPlus#194]
Had a ticket at the beginning of the month, it would appear the issue I have isn't fixed. Same issue with setwarp and jail, but I also checked into the rules with the same issue.

Setwarp: http://pastebin.com/48Jk8f5p

Setjail: http://pastebin.com/ahDkqU80

Addrule: http://pastebin.com/j7eE1PHH

**Comment by MarkehMe** [comment]
Thanks, there has been a change created now that will alter how this works.

Does this only happen when you're in a faction? or is this when you're not in a faction?

**Comment by bencerda1** [comment]
No errors when outside a faction, only when in one.

**Comment by MarkehMe** [comment]
Odd, thanks for reporting. I'll have a test build for this soon.
