### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by DaddyMew** [MarkehMe/FactionsPlus#196]
http://pastebin.com/whDD7zCs

**Comment by MarkehMe** [comment]
Did you recently upgrade from a different version of FactionsUUID?

**Comment by DraksterAU** [comment]
Using Factions26Patches?
Try the builds mentioned in the more recent issues. Might help.... But you definitely need the patches plugin for <2.6

**Comment by DraksterAU** [comment]
Sorry @markehme didn't see your comment

**Comment by DaddyMew** [comment]
No I been having the latest version which is "1.6.9.5-U0.1.18-b302".

Ill add the patches plugin and try and downgrade my current version of factionsplus.

**Comment by MarkehMe** [comment]
Appears I made some changes to the reflection utils at some point and did it incorrectly.. fixing now, will put a dev build here for you to try soon.

**Comment by MarkehMe** [comment]
[FactionsPlus.jar.zip](https://github.com/MarkehMe/FactionsPlus/files/138953/FactionsPlus.jar.zip)

**Comment by DaddyMew** [comment]
Works perfect now after updating the plugin, thankyou.

**Comment by MarkehMe** [comment]
Enjoy! :smiley:
