### ISSUE TITLE
f warp error:

### ISSUE THREAD

**Issue by alexsatellite** [MarkehMe/FactionsPlus#198]
http://hastebin.com/usetesotiw.avrasm

**Comment by MarkehMe** [comment]
Please provide some more information. The file ```plugins\FactionsPlus\logs\1457898712966.errorlog``` contains information that would be helpful, please upload this to a paste service and provide the link.

Is the player ByteMagic in a faction?

**Comment by MarkehMe** [comment]
Found the problem.. will be pushing a fix up soon.

**Comment by MarkehMe** [comment]
Here is a development build you can try, it should fix the issue.

[FactionsPlus.jar.zip](https://github.com/MarkehMe/FactionsPlus/files/173172/FactionsPlus.jar.zip)
