### ISSUE TITLE
Nothing saves

### ISSUE THREAD

**Issue by SirFaizdat** [MarkehMe/FactionsPlus#200]
When I set a faction warp, it will be stored in memory locally. However, when the server is restarted, the warp is gone. Also, the faction's YML file (in the fdata directory), nothing is ever updated.

There are no errors in the console.

**Comment by MarkehMe** [comment]
Can you explain your server setup a little more please? Have you changed the plugin directories? does config.yml exist?

**Comment by MarkehMe** [comment]
I've just done a quick test of this with beta build 6 and it appears to be working correctly.

**Comment by SirFaizdat** [comment]
This is my fdata file. http://hastebin.com/tiqadawimo.sm
This is my config.yml file. http://hastebin.com/elametayag.avrasm

Nothing appears to be writing at all.

**Comment by MarkehMe** [comment]
Can you please do the following:

* Stop the server, delete the FactionsPlus folder, start the server
* Check the console for errors after a full routine (start server, create warp, stop server) 
* Supply your Java versions (Java 8 is recommended)

**Comment by SirFaizdat** [comment]
There are absolutely no error messages in console from FactionsPlus.
Java version: 1.8.0_60

**Comment by MarkehMe** [comment]
I'm unable to reproduce this. Are you using Spigot for 1.9? Can you please provide your plugin versions.

**Comment by SirFaizdat** [comment]
I'm using PaperSpigot 1.8.8 with the latest version of MassiveCore, Factions, and FactionsPlus.

**Comment by MarkehMe** [comment]
I'm not sure how this will go with PaperSpigot, could you try using regular spigot and seeing if the issue is the same?
