### ISSUE TITLE
Warps

### ISSUE THREAD

**Issue by AirBrunt** [MarkehMe/FactionsPlus#201]
It won't allow me to use my warps from essentials anymore.
How can I fix this problem?

**Comment by MarkehMe** [comment]
We don't interact with essentials at all

**Comment by AirBrunt** [comment]
when I type /warp name it says you must be in a faction
I know /f warp does that but /war seems to be doing the same for me

**Comment by DraksterAU** [comment]
So this bug is the command alias has overridden essentials?

**Comment by AirBrunt** [comment]
Yes. my bad on not explaining it better. Is there away to fix?

**Comment by DraksterAU** [comment]
@markeheme will definitely resolve that if it is the issue... Just be patient :)

**Comment by DraksterAU** [comment]
Sorry I mean @markehme

**Comment by AirBrunt** [comment]
Aight thanks

**Comment by MarkehMe** [comment]
You mean it overrides ```/warp```?

**Comment by DraksterAU** [comment]
Yeah

**Comment by AirBrunt** [comment]
yes when faction plus is in it changes /warp <name> from essentials to a f warp. when its not in its all good

**Comment by MarkehMe** [comment]
We don't even reference Essentials in the project, I'm really not sure what could cause that. 

Are you 100% sure you didn't set an alias?

**Comment by AirBrunt** [comment]
I'm sure

**Comment by MarkehMe** [comment]
I'm really confused by this. Please work with me here! 

When you execute the command ```/warp``` it instead execute ```/f warp```?

**Comment by AirBrunt** [comment]
When I type /warp it says I need to be in a faction.
When factionsplus is not on the server I have no problem.

**Comment by DraksterAU** [comment]
@airbrunt please zip up your plugins and mstore folder and provide it via Dropbox link :)

**Comment by AirBrunt** [comment]
Plugins:
1. Essentials-2.x-SNAPSHOT
2. EssentialsChat-2.x-SNAPSHOT
3. EssentialsGeoIP-2.x-SNAPSHOT
4. EssentialsSpawn-2.x-SNAPSHOT
5. FactionChat
6. Factions
7. FactionsPlus
8. MassiveCore
A Essentials command: http://prntscr.com/ak9eko
Error message in chat: http://prntscr.com/ak9eyy
MStore: https://www.dropbox.com/s/v42ynxiy2nrmjby/mstore.zip?dl=0

I tested it in a 1.8 server and 1.9 test server and get the same results

**Comment by MarkehMe** [comment]
If you disable Essentials does this return to normal?

**Comment by AirBrunt** [comment]
If I disable Essentials I wont have my essentials warps.

**Comment by MarkehMe** [comment]
I'm not asking you to keep it disabled, just to see if this is Essentials or not. If you disable Essentials does this return to normal?

**Comment by AirBrunt** [comment]
Without essentials it says "/warp <name> [password=none]"

**Comment by AirBrunt** [comment]
Basicly trying to say that /warp is the same as /f warp
But I need /warp for essentials.

**Comment by DraksterAU** [comment]
@AirBrunt This is with Factions 2.8.7, isnt it?

**Comment by MarkehMe** [comment]
I understand that you want the /warp command for essentials. I was simply asking to test if it's an interaction issue, and it's not :sweat_smile: If you type ```/join``` does this work as if it was ```/f join```?

**Comment by AirBrunt** [comment]
Yes I'm using Factions 2.8.7.
As for /join it doesn't show up as a command.
/f join does work tho
