### ISSUE TITLE
FactionsPlus commands based on faction rank

### ISSUE THREAD

**Issue by Gerdon262** [MarkehMe/FactionsPlus#207]
Hello,

So I am loving your plugin! but I have 1 question / request.

Could you make it so that the commands can also be based on the faction rank like: Leader/Officer.
Because I have to make special ranks with the permission for setting a jail for example or when you have the permissions that the plugin wil look if the player is an leader / officer in the faction.

**Comment by DraksterAU** [comment]
FactionsPerms could do this?

**Comment by Gerdon262** [comment]
That is per zone, but I mean is can you not add a 'ReqPlayerIsOfficer' class and add a ReqPlayerIsOfficer and ReqPlayerIsLeader in the 'CmdSetJail' Class as requirement ?

**Comment by MarkehMe** [comment]
We're moving to ReqRankAtLeast instead now. 

https://github.com/MarkehMe/FactionsFramework/blob/master/src/me/markeh/factionsframework/command/requirements/ReqRankAtLeast.java
